LOCAL:
  DATABASE:
    MONGODB_HOST: TGTUXyvF+DS50X7CdFE7PHJR3GQ5s8cGJ3iGGzKuCzmHe+Zd0hN4a3s=
    MONGODB_PORT: ZJLUj93k6wzTYXug4HAyfQsTGjiSCfWzvo6HkmrYMzAbAPGuEQ==
    MONGODB_USER: ""
    MONGODB_PASSWORD: ""
    MONGODB_AUTH_DB: ++1KN0eSFPvSfdwaaiagAoyTU4HFB1oHmvfhMfyB7pch8OdyBQ==
    MONGODB_DATABASE: ""
UAT:
  DATABASE:
    MONGODB_HOST: testhost
    MONGODB_PORT: testport
    MONGODB_USER: testuser
    MONGODB_PASSWORD: testpassword
    MONGODB_AUTH_DB: testauthdb
    MONGODB_DATABASE: testdb
